sudo: required

services:
  - docker

script:
  - docker build -t mikandroid .
  - docker run -d mikandroid
  - docker ps -a
  - docker run mikandroid /bin/sh -c "android list && mvn -v && gradle -v && java -version && ant -version"
